classDiagram
    direction LR
    namespace controller {
      class RequestListController
    }
    namespace service {
      class IRequestService {
        + getMergeRequests(accessToken: String): List<RequestInfoForm>
      }

      class GitLabMergeRequestServiceImpl {
        - gitLabApiExecutor: GitLabApiExecutor
        + getMergeRequests(accessToken: String): List<RequestInfoForm>
        + executeGitLabApi(accessToken: String): List<GitLabMergeRequestApiResponseDto>
        + generateRequestInfoForm(responseDtos: List<GitLabMergeRequestApiResponseDto>): RequestInfoForm
      }
    }
    namespace external {
      class IApiExecutor {
        + getRequests(accessToken: String): List<GitLabMergeRequestApiResponseDto>
      }

      class GitLabApiExecutorImpl {
        + getRequests(accessToken: String): List<GitLabMergeRequestApiResponseDto>
      }
    }

    namespace presentation {
      class IPresenter {
        + toForm (requestDto: IRequest): RequestInfoForm
      }

      class GitLabMergeRequestPresenter {
        + toForm (requestDto: IRequest): RequestInfoForm
      }
    }

    %% controller
    RequestListController --> IRequestService
    RequestListController --> IPresenter

    %% service
    GitLabMergeRequestServiceImpl --|> IRequestService
    GitLabMergeRequestServiceImpl --> IApiExecutor

    %% external
    GitLabApiExecutorImpl --|> IApiExecutor

    %% presentation
    GitLabMergeRequestPresenter --|> IPresenter

