#spring.profiles.active: local
app:
  gitlab:
    project:
      id:
      accessToken:
    api:
      endpoint: https://gitlab.com/api/v4/projects/${app.gitlab.project.id}/merge_requests
logging:
  level:
    root: INFO
    io:
      github:
        tttol:
          mrls: DEBUG