spring:
  security:
    oauth2:
      client:
        provider:
          mrls-localhost:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: username
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys
        registration:
          mrls-localhost:
            client-id: hogehoge # set in application-env.yml
            client-secret: hogehoge # set in application-env.yml
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/mrls-localhost
            scope: read_api
            client-name: mrls-localhost
  thymeleaf:
    cache: false # apply html change without reloading app
    cache-period: 0
    prefix: file:src/main/resources/templates/
app:
  gitlab:
    project:
      id:
      accessToken:
    api:
      endpoint: https://gitlab.com/api/v4/projects/${app.gitlab.project.id}/merge_requests
logging:
  level:
    root: INFO
    io:
      github:
        tttol:
          mrls: DEBUG