app:
  gitlab:
    project:
      id: ${GITLAB_PROJECT_ID}
      accessToken: ${GITLAB_ACCESS_TOKEN}
    api:
      endpoint: https://gitlab.com/api/v4/projects/${app.gitlab.project.id}/merge_requests
logging:
  level:
    root: INFO
    io:
      github:
        tttol:
          mrls: DEBUG