app:
  gitlab:
    host: host
    project:
      id: id
      accessToken: token
    api:
      endpoint: https://${app.gitlab.host}/api/v4/projects/${app.gitlab.project.id}/merge_requests?state=opened
logging:
  level:
    root: INFO
    io:
      github:
        tttol:
          mrls: DEBUG